version: "3"

env:
  ENV: dev
  PACKAGES: ./...

dotenv: [".env", "{{.ENV}}/.env."]

tasks:
  init:
    desc: initialize requirements
    cmds:
      - swagger generate client -f https://developer.shortcut.com/api/rest/v3/shortcut.swagger.json --target pkg/shortcut/gen/
      - go mod download
  build:
    desc: Build in production mode
    cmds:
      - goreleaser release --clean
  build-snapshots:
    desc: Build in snapshot mode
    cmds:
      - goreleaser release --clean --snapshot
  lint:
    desc: lint the project
    cmds:
      - golangci-lint run $PACKAGES
  dev:
    desc: execute application code
    cmds:
      - go run cmd/cli/main.go {{.CLI_ARGS}}
  tests:
    desc: launch tests
    cmds:
      - go test -cover $PACKAGES
