---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - name: Setup go-swagger
        uses: ./.github/actions/setup-swagger
      - name: Generate client
        run: swagger generate client -f https://developer.shortcut.com/api/rest/v3/shortcut.swagger.json --target pkg/shortcut/gen/
      - name: Install Just
        uses: extractions/setup-just@v4
      - name: Tests
        run: |
          just tests
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
