---
name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - name: Setup go-swagger
        uses: ./.github/actions/setup-swagger
      - name: Generate client
        run: swagger generate client -f https://developer.shortcut.com/api/rest/v3/shortcut.swagger.json --target pkg/shortcut/gen/
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
