name: Release-Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          release-type: go
          default-branch: main
          changelog-types: |
            [
              {"type":"feat","section":"🚀 Features","hidden":false},
              {"type":"change","section":"🚀 Features","hidden":false},
              {"type":"deprecate","section":"⚠️ Changes","hidden":false},
              {"type":"remove","section":"⚠️ Changes","hidden":false},
              {"type":"fix","section":"🐞 Bug Fixes","hidden":false},
              {"type":"revert","section":"🐞 Bug Fixes","hidden":false},
              {"type":"security","section":"🐞 Bug Fixes","hidden":false},
              {"type":"perf","section":"✨ Polish","hidden":false},
              {"type":"refactor","section":"✨ Polish","hidden":false},
              {"type":"style","section":"✨ Polish","hidden":false},
              {"type":"build","section":"🧰 Other","hidden":false},
              {"type":"chore","section":"🧰 Other","hidden":false},
              {"type":"deps","section":"🧰 Other","hidden":true},
              {"type":"ci","section":"🧰 Other","hidden":true},
              {"type":"test","section":"🧪 Tests","hidden":false},
              {"type":"docs","section":"📚 Documentation","hidden":false}
            ]
